#!/bin/bash


tmpFile=$(mktemp)

for_dir_list(){
  local _dir=$1
  
  for x in $(ls $_dir)
  do
    if [ ! -d $_dir$x ];then
      echo $_dir$x >> $tmpFile

    else

      echo "==============$_dir$x===================" >> $tmpFile
      for_dir_list $_dir$x/
    fi
  done


}

[ -z $1 ] && rm $tmpFile && echo "Using : $0 Dir_Name" && exit 2
if [ -d $1 ];then
  
  for_dir_list $1
else
  echo "ERROR"
  exit 
fi

cp $tmpFile ./list.log

rm $tmpFile
